import { NextRequest, NextResponse } from "next/server";
import { timingSafeEqual } from "crypto";

/**
 * GET /api/meta/product-feed
 *
 * Public entry point for the Meta (Facebook/Instagram) Product Catalog feed.
 * Meta's Commerce Manager is told to fetch THIS URL on a schedule:
 *
 *     https://dazzle.com.bd/api/meta/product-feed?key=<META_FEED_TOKEN>
 *
 * The feed itself is generated by the .NET backend straight from the product
 * database (the only place that has every product's description, brand,
 * stock and price) — this route is a thin pass-through so that:
 *   - the feed lives on the SAME domain as the product pages/images it links
 *     to (Meta matches catalog items to website events by domain),
 *   - the backend host and its secret stay out of anything Meta (or anyone
 *     else) sees — same reason all browser API calls go through /api/proxy,
 *   - Cloudflare can cache the (multi-MB) XML so Meta's fetches don't hit the
 *     backend every time.
 *
 * Contract with the backend: see docs/meta-catalog-backend-todo.txt.
 *
 * Env (server-only — never NEXT_PUBLIC_*):
 *   META_FEED_TOKEN         secret that Meta must send as ?key=. If unset the
 *                           feed is public (it only contains public product
 *                           data), but setting it is recommended. The same
 *                           value is forwarded to the backend as the
 *                           X-Meta-Feed-Key header.
 *   META_FEED_UPSTREAM_URL  backend feed URL. Defaults to
 *                           ${API_BASE_URL}/api/meta/product-feed.
 */
export const dynamic = "force-dynamic";

const API_BASE_URL = process.env.API_BASE_URL || "https://apix.bigpoint.com.bd";
const UPSTREAM_URL = process.env.META_FEED_UPSTREAM_URL || `${API_BASE_URL}/api/meta/product-feed`;
// Generating a ~4,000-product XML from the database can take a while; far
// longer than the 30s budget the generic /api/proxy route gives a JSON call.
const UPSTREAM_TIMEOUT_MS = 90_000;

function keyMatches(provided: string | null, expected: string): boolean {
  if (!provided) return false;
  const a = Buffer.from(provided);
  const b = Buffer.from(expected);
  return a.length === b.length && timingSafeEqual(a, b);
}

export async function GET(request: NextRequest) {
  const token = process.env.META_FEED_TOKEN;

  if (token && !keyMatches(request.nextUrl.searchParams.get("key"), token)) {
    return new NextResponse("Invalid or missing feed key.", { status: 401 });
  }

  try {
    const upstream = await fetch(UPSTREAM_URL, {
      headers: {
        Accept: "application/xml",
        ...(token ? { "X-Meta-Feed-Key": token } : {}),
      },
      cache: "no-store",
      signal: AbortSignal.timeout(UPSTREAM_TIMEOUT_MS),
    });

    if (!upstream.ok || !upstream.body) {
      console.error(`[MetaFeed] upstream returned HTTP ${upstream.status}`);
      return new NextResponse("Product feed is temporarily unavailable.", {
        status: 502,
        headers: { "Cache-Control": "no-store" },
      });
    }

    const type = upstream.headers.get("content-type") || "";
    if (!/xml/i.test(type)) {
      // A JSON error page or an HTML login/WAF page must never be handed to
      // Meta as if it were the catalog — Meta would import it as a broken feed.
      console.error(`[MetaFeed] upstream did not return XML (content-type: "${type}")`);
      return new NextResponse("Product feed is temporarily unavailable.", {
        status: 502,
        headers: { "Cache-Control": "no-store" },
      });
    }

    return new NextResponse(upstream.body, {
      status: 200,
      headers: {
        "Content-Type": "application/xml; charset=utf-8",
        // Short shared-cache window: price/stock changes must show up in the
        // feed quickly, but Meta (and any retries) shouldn't each trigger a
        // full database export.
        "Cache-Control": "public, s-maxage=600, stale-while-revalidate=1800",
      },
    });
  } catch (error) {
    console.error("[MetaFeed] failed to fetch the upstream feed:", error);
    return new NextResponse("Product feed is temporarily unavailable.", {
      status: 502,
      headers: { "Cache-Control": "no-store" },
    });
  }
}
